export let ALL_PLAYERS = [
  { name:"Dev Rajput",role:"Batsman",dept:"Retail Sales",type:"Field",gender:"M"},
  { name:"Amiya Mandal",role:"Batsman",dept:"Retail Sales",type:"Field",gender:"M"},
  { name:"Adrash Kumar",role:"Batsman",dept:"Retail Sales",type:"Field",gender:"M"},
  { name:"Ronnie Dutta",role:"Batsman",dept:"Pharma Sales",type:"Field",gender:"M"},
  { name:"Vishnu Dayal",role:"Batsman",dept:"Product Service",type:"Field",gender:"M"},
  { name:"Dinesh Kumar M",role:"Batsman",dept:"Product Service",type:"Field",gender:"M"},
  { name:"Sanket Somanath Kakad",role:"All-Rounder",dept:"Retail Sales",type:"Field",gender:"M"},
  { name:"Anoop Anantha Dongre",role:"All-Rounder",dept:"Retail Sales",type:"Field",gender:"M"},
  { name:"Raghavendra J",role:"All-Rounder",dept:"Retail Sales",type:"Field",gender:"M"},
  { name:"Laxman Yogi",role:"All-Rounder",dept:"Retail Sales",type:"Field",gender:"M"},
  { name:"Manmohan Singh",role:"All-Rounder",dept:"Retail Sales",type:"Field",gender:"M"},
  { name:"Pradeep Kumar Pant",role:"All-Rounder",dept:"Retail Sales",type:"Field",gender:"M"},
  { name:"Doddi Avinash",role:"All-Rounder",dept:"Retail Sales",type:"Field",gender:"M"},
  { name:"Kunal Shankarrao Bante",role:"All-Rounder",dept:"Product Service",type:"Field",gender:"M"},
  { name:"Mohamed Khan",role:"All-Rounder",dept:"Product Service",type:"Field",gender:"M"},
  { name:"Aditya Kumar Sinha",role:"All-Rounder",dept:"Government Sales",type:"Field",gender:"M"},
  { name:"Chirag Jayantilal Gogri",role:"All-Rounder",dept:"Brand",type:"Field",gender:"M"},
  { name:"Shashank Pai",role:"Bowler",dept:"International Sales",type:"Field",gender:"M"},
  { name:"Blesson George Kurien",role:"Bowler",dept:"Retail Sales",type:"Field",gender:"M"},
  { name:"Mohd Junaid",role:"Bowler",dept:"Product Service",type:"Field",gender:"M"},
  { name:"Marichamy S S",role:"Bowler",dept:"Government Sales",type:"Field",gender:"M"},
  { name:"Yash Rampragat Varma",role:"Bowler",dept:"Retail Sales",type:"Field",gender:"M"},
  { name:"Rohini G",role:"Batsman",dept:"Human Resources",type:"HO",gender:"F"},
  { name:"Prajwal Anthony Dias",role:"Batsman",dept:"QA & Regulatory",type:"HO",gender:"M"},
  { name:"Lakshmeesha .",role:"Batsman",dept:"Operations",type:"HO",gender:"M"},
  { name:"Abhishek J N",role:"Batsman",dept:"Finance & Accounts",type:"HO",gender:"M"},
  { name:"Shreya A Bhandary",role:"Batsman",dept:"AI & ML",type:"HO",gender:"F"},
  { name:"Anand Sivaraman",role:"Batsman",dept:"CEO Office",type:"HO",gender:"M"},
  { name:"Shabeer Basha",role:"Batsman",dept:"Operations",type:"HO",gender:"M"},
  { name:"Praveena H P",role:"Batsman",dept:"Operations",type:"HO",gender:"F"},
  { name:"Harshith P Lad",role:"Batsman",dept:"QA & Regulatory",type:"HO",gender:"M"},
  { name:"Karibasava A",role:"Batsman",dept:"Operations",type:"HO",gender:"M"},
  { name:"Arun Kumar",role:"Batsman",dept:"Operations",type:"HO",gender:"M"},
  { name:"Dr. Koustav Chatterjee",role:"Batsman",dept:"Clinical Research",type:"HO",gender:"M"},
  { name:"Bharath Reddy",role:"Batsman",dept:"Product Service",type:"HO",gender:"M"},
  { name:"Rakesh",role:"Batsman",dept:"Operations",type:"HO",gender:"M"},
  { name:"Chethan R",role:"Batsman",dept:"Operations",type:"HO",gender:"M"},
  { name:"Chidananda M",role:"Batsman",dept:"Operations",type:"HO",gender:"M"},
  { name:"Shriharsha S M",role:"Batsman",dept:"QA & Regulatory",type:"HO",gender:"M"},
  { name:"Manu H S",role:"Batsman",dept:"Operations",type:"HO",gender:"M"},
  { name:"Ajit D K",role:"Batsman",dept:"Operations",type:"HO",gender:"M"},
  { name:"Sudarshan P N",role:"Batsman",dept:"Operations",type:"HO",gender:"M"},
  { name:"Alok Kumar Gupta",role:"All-Rounder",dept:"R&D",type:"HO",gender:"M"},
  { name:"Dass B",role:"All-Rounder",dept:"R&D",type:"HO",gender:"M"},
  { name:"Aruna Devi R",role:"All-Rounder",dept:"Clinical Research",type:"HO",gender:"F"},
  { name:"Ankith P",role:"All-Rounder",dept:"Operations",type:"HO",gender:"M"},
  { name:"Rohini M",role:"All-Rounder",dept:"International Sales",type:"HO",gender:"F"},
  { name:"Shweta Binoy",role:"All-Rounder",dept:"Human Resources",type:"HO",gender:"F"},
  { name:"M Suriya",role:"All-Rounder",dept:"Operations",type:"HO",gender:"M"},
  { name:"K Basavesha",role:"All-Rounder",dept:"Operations",type:"HO",gender:"M"},
  { name:"Manikandan S",role:"All-Rounder",dept:"Operations",type:"HO",gender:"M"},
  { name:"Dushyantsinh A Jadeja",role:"All-Rounder",dept:"CEO Office",type:"HO",gender:"M"},
  { name:"Huded Amith",role:"All-Rounder",dept:"R&D",type:"HO",gender:"M"},
  { name:"Chethan A",role:"All-Rounder",dept:"QA & Regulatory",type:"HO",gender:"M"},
  { name:"Nithyasree M",role:"All-Rounder",dept:"QA & Regulatory",type:"HO",gender:"F"},
  { name:"Richard Nickelson",role:"All-Rounder",dept:"DaaS",type:"HO",gender:"M"},
  { name:"Anila Kumari C",role:"All-Rounder",dept:"Admin",type:"HO",gender:"F"},
  { name:"Pranav J",role:"All-Rounder",dept:"Product Mgmt",type:"HO",gender:"M"},
  { name:"Renuka M Ratnaparkhi",role:"All-Rounder",dept:"QA & Regulatory",type:"HO",gender:"F"},
  { name:"Suraj U Hiremath",role:"All-Rounder",dept:"Operations",type:"HO",gender:"M"},
  { name:"Shivakumar V",role:"All-Rounder",dept:"Operations",type:"HO",gender:"M"},
  { name:"Jesto Raju",role:"All-Rounder",dept:"R&D",type:"HO",gender:"M"},
  { name:"Karthik Shetty",role:"All-Rounder",dept:"AI & ML",type:"HO",gender:"M"},
  { name:"Jeevith K H",role:"All-Rounder",dept:"QA & Regulatory",type:"HO",gender:"M"},
  { name:"Shiva Kumar A",role:"All-Rounder",dept:"QA & Regulatory",type:"HO",gender:"M"},
  { name:"Chandhu H M",role:"All-Rounder",dept:"QA & Regulatory",type:"HO",gender:"M"},
  { name:"Yobhraj Daithota",role:"All-Rounder",dept:"QA & Regulatory",type:"HO",gender:"M"},
  { name:"Shashank S Acharya",role:"All-Rounder",dept:"Operations",type:"HO",gender:"M"},
  { name:"G Shekar",role:"All-Rounder",dept:"Operations",type:"HO",gender:"M"},
  { name:"Prasanna L Kulakarni",role:"All-Rounder",dept:"QA & Regulatory",type:"HO",gender:"M"},
  { name:"Sachin S Munji",role:"Bowler",dept:"R&D",type:"HO",gender:"M"},
  { name:"Selvaraj V",role:"Bowler",dept:"R&D",type:"HO",gender:"M"},
  { name:"Preethi U Pillai",role:"Bowler",dept:"Operations",type:"HO",gender:"F"},
  { name:"Prakash H B",role:"Bowler",dept:"R&D",type:"HO",gender:"M"},
].map((p, i) => ({ ...p, id: i }));

export const TEAMS_INIT = [
  { id:1, name:"RCB", color:"#e74c3c", budget:1000000, players:[], captain:null, viceCaptain:null },
  { id:2, name:"Remidio Power Star", color:"#2980b9", budget:1000000, players:[], captain:null, viceCaptain:null },
  { id:3, name:"Remidio Falcon", color:"#e67e22", budget:1000000, players:[], captain:null, viceCaptain:null },
  { id:4, name:"Remidio Strikers", color:"#f39c12", budget:1000000, players:[], captain:null, viceCaptain:null },
  { id:5, name:"Remidio Rangers", color:"#8e44ad", budget:1000000, players:[], captain:null, viceCaptain:null },
  { id:6, name:"Royal Warriors", color:"#e67e22", budget:1000000, players:[], captain:null, viceCaptain:null },
];

export const DEFAULT_PASSWORDS = {
  admin: "rpl@admin2026",
  1: "thunder@01",
  2: "royal@02",
  3: "green@03",
  4: "golden@04",
  5: "purple@05",
  6: "orange@06",
};

export const ROLE_ICON = { Batsman: "🏏", "All-Rounder": "⭐", Bowler: "🎯", "Wicket-Keeper": "🧤" };
export const BASE_PRICE = 50000;
export const BID_INC = 5000;
export const MAX_SQUAD = 15;
export const MIN_SQUAD = 11;
export const TIMER_DURATION = 15;
export const MIN_WOMEN = 2;
export const MIN_BATSMEN = 5;
export const MIN_BOWLERS = 5;
export const MIN_WK = 1;
